var title = document.createElement('div');
title.setAttribute('class', 'my-class');
title.style.backgroundColor = "yellow";
title.innerText = 'Element 1';
document.body.appendChild(title);
var titleOne = document.createElement('div');
titleOne.setAttribute('class', 'my-class');
titleOne.style.backgroundColor = "orange";
titleOne.innerText = 'Element 2';
document.body.appendChild(titleOne);